[FIX] ADD generate invoice & invoice report from pos sale order
akretion/pos pull request #5
Opened 2018-04-13 10:30 UTC by mourad-ehm

2018-04-25 08:41 UTC, hparfr requested changes
to_invoice ne doit pas être un nouvel état de sale_order_state.
Il ne faut pas générer la facture dans sale_oder mais à la demande (fait par ton appel en js dans .then())

2018-04-25 09:22 UTC, mourad-ehm commented
En fait, j'ai repris ce qui est fait dans le pos standard où la facture, comme le BL d'ailleur, est générée coté python au même temps que la commande (si elle demandé). Le then permet just de télécharger le PDF de la facture.
Sinon il faut pas non plus que le statue "delivered" soit sur la commande pour avoir un fonctionnement homogène sur tous le flux.

2018-04-25 09:36 UTC, hparfr commented
ok, en ce cas utilise order_data['to_invoice'].

2018-04-25 10:52 UTC, mourad-ehm commented
Ok

2018-04-25 14:59 UTC, mourad-ehm commented
Ok

2018-05-17 13:30 UTC, mourad-ehm commented
@hparfr tu peux merger stp ?

2018-05-31 08:02 UTC, hparfr commented on pos_order_to_sale_order/static/src/js/ui_widgets.js
> +                    console.log('on fait rien')
a virer

2018-05-31 08:02 UTC, hparfr commented on pos_order_to_sale_order/static/src/js/product_screen.js
> +                    console.log('affiche bt inv')
a virer

2018-05-31 08:02 UTC, hparfr commented on pos_order_to_sale_order/static/src/js/product_screen.js
> +                    console.log('masquer bt inv')
idem

2018-05-31 08:03 UTC, hparfr commented on pos_order_to_sale_order/static/src/js/product_screen.js
> +                    console.log(result)
idem

2018-10-08 13:06 UTC, mourad-ehm commented
ping @hparfr

2018-10-15 10:12 UTC, hparfr approved these changes

2018-10-15 10:12 UTC, merged